.TH sasl_oauthbearer 5 "May 2025" "crudeoauth" "File Formats and Conventions"
.SH NAME
OAUTHBEARER \- SASL mechanism for OAuth 2.0 bearer token authentication
.SH SYNOPSIS
.B /etc/ldap/sasl2/slapd.conf
.br
SASL configuration file for OpenLDAP (or other SASL consumers).
.SH DESCRIPTION
The
.B OAUTHBEARER
SASL mechanism enables client authentication using OAuth 2.0 access tokens, in accordance with
RFC 7628 (OAuth 2.0 SASL mechanism) and RFC 9068 (JWT profile for access tokens).
.PP
This mechanism is implemented via the
.B crudeoauth
plugin, which validates JWTs against trusted JWKS URIs and checks token claims.
.SH CONFIGURATION
Configuration options are specified in the SASL configuration file, commonly located at
.I /etc/ldap/sasl2/slapd.conf
for OpenLDAP servers.
.TP
.B mech_list
Must include
.BR OAUTHBEARER .
.TP
.B oauthbearer_grace
Specifies the allowed time drift (in seconds) when validating tokens. Example:
.B 3
.TP
.B oauthbearer_userid
JWT claim name used to derive the SASL authentication identity (authcid). Example:
.B preferred_username
.TP
.B oauthbearer_trusted_jwks0
Path to a JWKS file containing trusted public keys of the authorization server.
.TP
.B oauthbearer_trusted_iss0
Expected
.B iss
(Issuer) claim value. Tokens from other issuers are rejected.
.TP
.B oauthbearer_trusted_aud0
Expected
.B aud
(Audience) claim value. Required as per RFC 9068.
.TP
.B oauthbearer_trusted_azp0
Expected
.B azp
(Authorized Party) claim. Optional, provides additional validation.
.TP
.B oauthbearer_required_scope0
Specifies a required
.B scope
claim value. Optional, useful for fine-grained access control.
.TP
.B oauthbearer_no_tls
Optional, disable the enforcement of TLS encrypted connections by setting to
.B 1
.SH MAPPING TO LDAP DN
After successful SASL bind, OpenLDAP provides a DN such as:
.IP
uid=username,cn=oauthbearer,cn=auth
.PP
To map this to a DIT DN, use
.B authz-regexp
in
.I slapd.conf
as follows:
.PP
.nf
authz-regexp
    uid=([^,]*),cn=oauthbearer,cn=auth
    ldap:///dc=example,dc=org??sub?uid=$1
.fi
.SH SEE ALSO
.BR saslauthd (8),
.BR slapd (8),
.BR pam_oauthbearer (5),
RFC 7628,
RFC 9068
.SH AUTHOR
Univention GmbH
.SH HOMEPAGE
https://github.com/univention/crudeoauth
